### ISSUE TITLE
Add Secondary Color

### ISSUE THREAD

**Issue by mattjared** [xxhomey19/nba-color#14]
Similar to the `getMainColor` method that returns a hex value it would be great if there was a secondary color that returned a hex value.

**Comment by xxhomey19** [comment]
Hi, this is a good idea but it's hard to determine which color is the secondary color for each team. Any suggestion?

**Comment by mattjared** [comment]
Took a stab at it really quickly just as an idea. Totally cool to change any of em. 

https://github.com/xxhomey19/nba-color/compare/master...mattjared:patch-1

**Comment by xxhomey19** [comment]
It's now available on version 1.4.0 :)

**Comment by mattjared** [comment]
Sweet!! Thanks for letting me chip in. 💯
